name: build-wheels

on:
  push:
    branches:
      - 'stable'
  pull_request:
    branches:
      - 'stable'

env:
  CIBW_ARCHS: auto64
  CIBW_BUILD_VERBOSITY: 2

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    name: ${{ matrix.os }} / ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Build Wheels"
        env:
          CIBW_BUILD: \*manylinux\*
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_ALL: "./scripts/cibw_install_deps.sh"
          CIBW_REPAIR_WHEEL_COMMAND: "auditwheel show {wheel} && auditwheel repair -w {dest_dir} {wheel} --exclude libcuda.so.1 --exclude libvulkan.so.1"
        run: |
          python -m pip install -U cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse
      - name: "Upload Wheels"
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [ 13, 15 ]
    name: macos-${{ matrix.os }}
    runs-on: macos-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Setup LLVM"
        run: |
          brew install --overwrite python@3.12
          brew install --overwrite llvm molten-vk
      - name: "Build Wheels"
        run: |
          if [ "${{ matrix.os }}" = "13" ]; then
            export CC=/usr/local/opt/llvm/bin/clang
            export CXX=/usr/local/opt/llvm/bin/clang++
          else
            export CC=/opt/homebrew/opt/llvm/bin/clang
            export CXX=/opt/homebrew/opt/llvm/bin/clang++
          fi
          python3 -m pip install -U cibuildwheel --break-system-packages
          for dep_target in {13..${{ matrix.os }}}; do
            export MACOSX_DEPLOYMENT_TARGET=${dep_target}.0
            python3 -m cibuildwheel --output-dir wheelhouse
          done
      - name: "Upload Wheels"
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build-windows:
    name: windows-2025
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Setup Vulkan SDK"
        uses: johnnynunez/setup-vulkan-sdk@v1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
      - name: "Setup CUDA"
        uses: Jimver/cuda-toolkit@v0.2.22
        with:
          cuda: 12.8.1
          sub-packages: '[ "cudart", "nvrtc", "nvrtc_dev", "nvjitlink", "nvcc", "nvtx" ]'
      - name: "Setup Ninja"
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1
      - name: "Build Wheels"
        shell: cmd
        run: |
          python -m pip install -U cibuildwheel
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          python -m cibuildwheel --output-dir wheelhouse
      - name: "Upload Wheels"
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
